[package]
name = "scattering_solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quantum ={ path = "../quantum" }
nalgebra = { version = "0.32.1", features = ["rand"] }
num-traits = "0.2.15"
num = "0.4.0"